name: Medtronic ENT Newsletter
on:
  schedule:
    - cron: '0 0 1 * *'  # UTC 00:00 = 한국 시간 09:00 매월 1일
  workflow_dispatch:

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run newsletter script
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          HIWORKS_API_URL: ${{ secrets.HIWORKS_API_URL }}
          HIWORKS_API_TOKEN: ${{ secrets.HIWORKS_API_TOKEN }}
        run: node scripts/send-newsletter.mjs
